-- This file is automatically generated by Prisma
-- Do not edit manually

-- CreateEnum for DraftStatus
CREATE TABLE "_prisma_migrations" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "checksum" TEXT NOT NULL,
    "finished_at" DATETIME,
    "migration_name" TEXT NOT NULL,
    "logs" TEXT,
    "rolled_back_at" DATETIME,
    "started_at" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "applied_steps_count" INTEGER NOT NULL DEFAULT 0
);

-- Enhanced ReviewDraft schema
CREATE TABLE "review_drafts" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "bookId" TEXT,
    "title" TEXT,
    "content" TEXT NOT NULL,
    "metadata" TEXT NOT NULL DEFAULT '{}',
    "bookData" TEXT,
    "status" TEXT NOT NULL DEFAULT 'DRAFT',
    "version" INTEGER NOT NULL DEFAULT 1,
    "expiresAt" DATETIME NOT NULL,
    "lastAccessed" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "review_drafts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "review_drafts_bookId_fkey" FOREIGN KEY ("bookId") REFERENCES "Book" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- Audit table
CREATE TABLE "review_draft_audit" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "draftId" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "oldData" TEXT,
    "newData" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "review_draft_audit_draftId_fkey" FOREIGN KEY ("draftId") REFERENCES "review_drafts" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "review_draft_audit_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Optimized indexes
CREATE INDEX "review_drafts_user_drafts_timeline_idx" ON "review_drafts"("userId", "updatedAt" DESC);
CREATE INDEX "review_drafts_cleanup_queue_idx" ON "review_drafts"("expiresAt", "status");
CREATE INDEX "review_drafts_status_activity_idx" ON "review_drafts"("status", "lastAccessed");
CREATE INDEX "review_drafts_book_drafts_idx" ON "review_drafts"("bookId");
CREATE INDEX "review_drafts_user_status_idx" ON "review_drafts"("userId", "status");

-- Audit table indexes
CREATE INDEX "review_draft_audit_draftId_createdAt_idx" ON "review_draft_audit"("draftId", "createdAt");
CREATE INDEX "review_draft_audit_userId_createdAt_idx" ON "review_draft_audit"("userId", "createdAt");