/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as LoginImport } from './routes/login';
import { Route as BooksBooksIdImport } from './routes/books.$bookId';
import { Route as ProfileUserIdImport } from './routes/profile.$userId';
import { Route as ReviewReviewIdImport } from './routes/review.$reviewId';
// Create/Update Routes
const IndexRoute = IndexImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
});
const LoginRoute = LoginImport.update({
    path: '/login',
    getParentRoute: () => rootRoute,
});
const BooksBooksIdRoute = BooksBooksIdImport.update({
    path: '/books/$bookId',
    getParentRoute: () => rootRoute,
});
const ProfileUserIdRoute = ProfileUserIdImport.update({
    path: '/profile/$userId',
    getParentRoute: () => rootRoute,
});
const ReviewReviewIdRoute = ReviewReviewIdImport.update({
    path: '/review/$reviewId',
    getParentRoute: () => rootRoute,
});
// Create and export the route tree
export const routeTree = rootRoute.addChildren({
    IndexRoute,
    LoginRoute,
    BooksBooksIdRoute,
    ProfileUserIdRoute,
    ReviewReviewIdRoute
});
/* prettier-ignore-end */ 
